title: Custom Intelligent Hardware
logo: /assets/img/cihlog.png
description: Chixiao Chen, Ph.D <br />Ass. Prof @ Fudan University <br />We focus on Algorithm/Software/Hardware/Chip Codesign. <br />Contact me by: <br />cxchen@fudan.edu.cn
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
