title: Custom Intelligent Hardware
logo: /assets/img/cihlog.png
description: Chixiao Chen, Ass. Prof @ Fudan University, We are working on Algorithm/Software/Hardware/Chip Codesign.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
