title: Custom Intelligent Hardware
logo: /assets/img/cihlog.png
description: Chixiao Chen, Ph.D <br />Ass. Prof in Fudan University, Shanghai, China <br />Contact me by cxchen@fudan.edu.cn
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
